language: python
python: "3.5"
sudo: false
env:
  - TOX_ENV=py27
  - TOX_ENV=py35
matrix:
  fast_finish: true
install:
  - pip install tox codecov
script:
  - tox -e $TOX_ENV
after_success:
  codecov
notifications:
  email: false
